package views;

public class Cliente_Viajes_Completos extends javax.swing.JFrame {

    /**
     * Creates new form Cliente_Viajes_Completos
     */
    public Cliente_Viajes_Completos() {
        initComponents();
        setSize(720, 520);//Para que se queden las medidas que le dimos
        setResizable(false);//Para que el usuario no pueda modificar el tamaño.
        setTitle("Viajes Completados");//Para colocar un titulo a la ventana
        setLocationRelativeTo(null);//Centra la pantalla
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_completados_atras = new javax.swing.JButton();
        btn_completados_factura = new javax.swing.JButton();
        btn_completados_buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_completados_id = new javax.swing.JTextField();
        txt_completados_fecha_viaje = new javax.swing.JTextField();
        txt_completados_destino = new javax.swing.JTextField();
        txt_completados_precio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_completados_conductor = new javax.swing.JTextField();
        txt_completados_tipo_vehiculo = new javax.swing.JTextField();
        txt_completados_matricula = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        viajes_completados_tabla = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txt_completados_buscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(43, 81, 132));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 520));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 118, 0));
        jLabel1.setText("Viajes Completados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        btn_completados_atras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_completados_atras.setText("Atrás");
        jPanel1.add(btn_completados_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        btn_completados_factura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_completados_factura.setText("Factura");
        jPanel1.add(btn_completados_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 80, -1));

        btn_completados_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_completados_buscar.setText("Buscar");
        jPanel1.add(btn_completados_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 80, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de Viaje:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destino:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 20));
        jPanel1.add(txt_completados_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 80, -1));
        jPanel1.add(txt_completados_fecha_viaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 150, -1));
        jPanel1.add(txt_completados_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 150, -1));
        jPanel1.add(txt_completados_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Conductor:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo de Vehículo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Matricula:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, 30));
        jPanel1.add(txt_completados_conductor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 150, -1));
        jPanel1.add(txt_completados_tipo_vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 150, -1));
        jPanel1.add(txt_completados_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 150, -1));

        viajes_completados_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Destino", "Precio", "Conductor", "Tipo de Vehiculo", "Matricula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viajes_completados_tabla);
        if (viajes_completados_tabla.getColumnModel().getColumnCount() > 0) {
            viajes_completados_tabla.getColumnModel().getColumn(0).setResizable(false);
            viajes_completados_tabla.getColumnModel().getColumn(0).setPreferredWidth(10);
            viajes_completados_tabla.getColumnModel().getColumn(1).setResizable(false);
            viajes_completados_tabla.getColumnModel().getColumn(2).setResizable(false);
            viajes_completados_tabla.getColumnModel().getColumn(3).setResizable(false);
            viajes_completados_tabla.getColumnModel().getColumn(3).setPreferredWidth(20);
            viajes_completados_tabla.getColumnModel().getColumn(4).setResizable(false);
            viajes_completados_tabla.getColumnModel().getColumn(5).setResizable(false);
            viajes_completados_tabla.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 670, 120));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Buscar:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));
        jPanel1.add(txt_completados_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente_Viajes_Completos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente_Viajes_Completos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente_Viajes_Completos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente_Viajes_Completos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente_Viajes_Completos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_completados_atras;
    private javax.swing.JButton btn_completados_buscar;
    private javax.swing.JButton btn_completados_factura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_completados_buscar;
    private javax.swing.JTextField txt_completados_conductor;
    private javax.swing.JTextField txt_completados_destino;
    private javax.swing.JTextField txt_completados_fecha_viaje;
    private javax.swing.JTextField txt_completados_id;
    private javax.swing.JTextField txt_completados_matricula;
    private javax.swing.JTextField txt_completados_precio;
    private javax.swing.JTextField txt_completados_tipo_vehiculo;
    private javax.swing.JTable viajes_completados_tabla;
    // End of variables declaration//GEN-END:variables
}
