package views;

import controlador.ReservasControlador;
import controlador.Solicitar_ServicioControlador;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import static modelo.Registro_ClienteDao.*;
import static modelo.Registro_ClienteDao.username_user;
import modelo.Reservas;
import modelo.ReservasDao;
import modelo.SolicitarServicio;
import modelo.Solicitar_ServicioDao;

public class Cliente extends javax.swing.JFrame {

    //Solicitar Servicio
    SolicitarServicio servicio = new SolicitarServicio();
    Solicitar_ServicioDao servicio_dao = new Solicitar_ServicioDao();
    Reservas reserva = new Reservas();
    ReservasDao reserva_dao = new ReservasDao();

    public Cliente() {
        initComponents();
        setSize(1000, 560);//Para que se queden las medidas que le dimos
        setResizable(false);//Para que el usuario no pueda modificar el tamaño.
        setTitle("CLIENTE");//Para colocar un titulo a la ventana
        setLocationRelativeTo(null);//Impide mover la ventana
        titleInterface();
        obtenerFechaHora();
        this.repaint();

        //Controlador de solicitar Servicio
        Solicitar_ServicioControlador soli_servicio = new Solicitar_ServicioControlador(servicio, servicio_dao, this);
        
        //Controlador de reservas
        ReservasControlador reservar = new ReservasControlador(reserva, reserva_dao, this);
    }

    public String titleInterface() {
        label_name_user.setText(username_user);
        label_rol_user.setText(rol);
        return rol.trim();
    }


    public boolean obtenerFechaHora(){
        // Obtener la fecha actual
        LocalDate fechaActual = LocalDate.now();

        // Obtener la hora actual
        LocalTime horaActual = LocalTime.now();

        // Formatear la fecha y la hora como cadenas
        String fechaFormateada = fechaActual.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        String horaFormateada = horaActual.format(DateTimeFormatter.ofPattern("HH:mm:ss"));

        // Crear la etiqueta y establecer el texto
       
        jLabel_usuario_fecha.setText( fechaFormateada ); // horaFormateada
        jLabel_usuario_hora.setText(horaFormateada);
         return  true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPSolicitar_Servicio = new javax.swing.JPanel();
        jLServicio = new javax.swing.JLabel();
        jPReservas = new javax.swing.JPanel();
        jLReservas = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label_name_user = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        label_rol_user = new javax.swing.JLabel();
        jLabel_usuario_fecha = new javax.swing.JLabel();
        jLabel_usuario_hora = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_solicitar_cancelar = new javax.swing.JButton();
        btn_solicitar_aceptar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_solicitar_destino = new javax.swing.JTextField();
        txt_soliticar_ubicacion = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_reservas_cancelar = new javax.swing.JButton();
        btn_reservas_aceptar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txt_reservas_dia = new javax.swing.JTextField();
        txt_reservas_destino = new javax.swing.JTextField();
        txt_reservas_ubicacion = new javax.swing.JTextField();
        txt_reservas_hora = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        btn_configuracion_foto = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        txt_configuracion_usuario = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txt_configuracion_nombres = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txt_configuracion_cedula = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txt_configuracion_provincia = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txt_configuracion_telefono = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txt_configuracion_email = new javax.swing.JTextField();
        btn_configuracion_cambio_contraseña = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        btn_configuracion_cancelar = new javax.swing.JButton();
        btn_configuracion_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("  Elija una opción a realizar");
        jLabel4.setAutoscrolls(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 40));

        jPSolicitar_Servicio.setBackground(new java.awt.Color(255, 255, 102));

        jLServicio.setBackground(new java.awt.Color(255, 255, 102));
        jLServicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLServicio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLServicio.setText("Solicitar Servicio      ");
        jLServicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPSolicitar_ServicioLayout = new javax.swing.GroupLayout(jPSolicitar_Servicio);
        jPSolicitar_Servicio.setLayout(jPSolicitar_ServicioLayout);
        jPSolicitar_ServicioLayout.setHorizontalGroup(
            jPSolicitar_ServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPSolicitar_ServicioLayout.setVerticalGroup(
            jPSolicitar_ServicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLServicio, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPSolicitar_Servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 190, 60));

        jPReservas.setBackground(new java.awt.Color(255, 255, 102));

        jLReservas.setBackground(new java.awt.Color(255, 255, 102));
        jLReservas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLReservas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLReservas.setText("Reservas            ");
        jLReservas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPReservasLayout = new javax.swing.GroupLayout(jPReservas);
        jPReservas.setLayout(jPReservasLayout);
        jPReservasLayout.setHorizontalGroup(
            jPReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPReservasLayout.setVerticalGroup(
            jPReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLReservas, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 190, 60));

        jPanel6.setBackground(new java.awt.Color(255, 255, 102));

        jLabel11.setBackground(new java.awt.Color(255, 255, 102));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Actividad            ");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, 60));

        jPanel7.setBackground(new java.awt.Color(255, 255, 102));

        jLabel12.setBackground(new java.awt.Color(255, 255, 102));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Configuración       ");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 190, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 190, 430));

        jPanel2.setBackground(new java.awt.Color(242, 120, 29));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(242, 120, 29));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Bienvenido al Sistema Uber");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 520, -1));

        label_name_user.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(label_name_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 100, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Cerrar Sesión");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, -1, -1));

        label_rol_user.setForeground(new java.awt.Color(242, 120, 29));
        jPanel2.add(label_rol_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 70, 20));

        jLabel_usuario_fecha.setForeground(new java.awt.Color(242, 120, 29));
        jPanel2.add(jLabel_usuario_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 100, 20));

        jLabel_usuario_hora.setForeground(new java.awt.Color(242, 120, 29));
        jPanel2.add(jLabel_usuario_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 90, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 110));

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 255));

        jPanel8.setBackground(new java.awt.Color(74, 101, 191));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Elija Su Destino");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Elija Su Ubicación");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        btn_solicitar_cancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_solicitar_cancelar.setText("Cancelar");
        jPanel8.add(btn_solicitar_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        btn_solicitar_aceptar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_solicitar_aceptar.setText("Aceptar");
        jPanel8.add(btn_solicitar_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        jLabel7.setText("jLabel7");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 100, 80));

        jLabel8.setText("jLabel8");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 100, 80));
        jPanel8.add(txt_solicitar_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 550, -1));
        jPanel8.add(txt_soliticar_ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 550, -1));

        jTabbedPane1.addTab("tab1", jPanel8);

        jPanel9.setBackground(new java.awt.Color(74, 101, 191));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("¿Para cúando solicita su viaje?");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Día/Mes/Año :");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Hora:");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("¿A donde desea ir?");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("¿Dónde estará Ubicado?");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        btn_reservas_cancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_reservas_cancelar.setText("Cancelar");
        jPanel9.add(btn_reservas_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        btn_reservas_aceptar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_reservas_aceptar.setText("Aceptar");
        jPanel9.add(btn_reservas_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        jLabel19.setText("jLabel19");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 130, 120));

        txt_reservas_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_reservas_diaActionPerformed(evt);
            }
        });
        jPanel9.add(txt_reservas_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 120, 25));
        jPanel9.add(txt_reservas_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 500, -1));
        jPanel9.add(txt_reservas_ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 500, -1));
        jPanel9.add(txt_reservas_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 120, 25));

        jTabbedPane1.addTab("tab2", jPanel9);

        jPanel10.setBackground(new java.awt.Color(74, 101, 191));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 102, 0));
        jLabel20.setText("Historial de Viajes");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Elija una opción a ");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 250, 80));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Revisar");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabel23.setText("jLabel23");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 204));
        jLabel25.setText("Viaje en Curso");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 210, 190));

        jLabel24.setText("jLabel24");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 204));
        jLabel26.setText("Viajes Completados");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jPanel10.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 210, 190));

        jTabbedPane1.addTab("tab3", jPanel10);

        jPanel11.setBackground(new java.awt.Color(74, 101, 191));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("jLabel27");
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 100));

        btn_configuracion_foto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_configuracion_foto.setText("Editar Foto");
        jPanel11.add(btn_configuracion_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Usuario:");
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        jPanel11.add(txt_configuracion_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 280, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Nombres y Apellidos:");
        jPanel11.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));
        jPanel11.add(txt_configuracion_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 280, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Cédula o Ruc:");
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));
        jPanel11.add(txt_configuracion_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 120, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Provincia:");
        jPanel11.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));
        jPanel11.add(txt_configuracion_provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 280, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Teléfono:");
        jPanel11.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));
        jPanel11.add(txt_configuracion_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 120, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Correo Electrónico:");
        jPanel11.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));
        jPanel11.add(txt_configuracion_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 250, -1));

        btn_configuracion_cambio_contraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_configuracion_cambio_contraseña.setText("Cambiar Contraseña");
        jPanel11.add(btn_configuracion_cambio_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, -1));

        jLabel34.setText("jLabel34");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 150, 130));

        btn_configuracion_cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_configuracion_cancelar.setText("Cancelar");
        jPanel11.add(btn_configuracion_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, -1, -1));

        btn_configuracion_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_configuracion_guardar.setText("Guardar");
        jPanel11.add(btn_configuracion_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, -1, -1));

        jTabbedPane1.addTab("tab4", jPanel11);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 1020, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_reservas_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_reservas_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_reservas_diaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_configuracion_cambio_contraseña;
    private javax.swing.JButton btn_configuracion_cancelar;
    private javax.swing.JButton btn_configuracion_foto;
    private javax.swing.JButton btn_configuracion_guardar;
    public javax.swing.JButton btn_reservas_aceptar;
    public javax.swing.JButton btn_reservas_cancelar;
    public javax.swing.JButton btn_solicitar_aceptar;
    public javax.swing.JButton btn_solicitar_cancelar;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLReservas;
    public javax.swing.JLabel jLServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel_usuario_fecha;
    public javax.swing.JLabel jLabel_usuario_hora;
    public javax.swing.JPanel jPReservas;
    public javax.swing.JPanel jPSolicitar_Servicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel label_name_user;
    public javax.swing.JLabel label_rol_user;
    private javax.swing.JTextField txt_configuracion_cedula;
    private javax.swing.JTextField txt_configuracion_email;
    private javax.swing.JTextField txt_configuracion_nombres;
    private javax.swing.JTextField txt_configuracion_provincia;
    private javax.swing.JTextField txt_configuracion_telefono;
    private javax.swing.JTextField txt_configuracion_usuario;
    public javax.swing.JTextField txt_reservas_destino;
    public javax.swing.JTextField txt_reservas_dia;
    public javax.swing.JTextField txt_reservas_hora;
    public javax.swing.JTextField txt_reservas_ubicacion;
    public javax.swing.JTextField txt_solicitar_destino;
    public javax.swing.JTextField txt_soliticar_ubicacion;
    // End of variables declaration//GEN-END:variables
}
