package views;

public class Cliente_Informacion_Conductor extends javax.swing.JFrame {

    /**
     * Creates new form Cliente_Informacion_Conductor
     */
    public Cliente_Informacion_Conductor() {
        initComponents();
        setSize(660, 520);//Para que se queden las medidas que le dimos
        setResizable(false);//Para que el usuario no pueda modificar el tamaño.
        setTitle("Información del Conductor");//Para colocar un titulo a la ventana
        setLocationRelativeTo(null);//Centra la pantalla
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_informacion_conductor_calificar = new javax.swing.JButton();
        btn_informacion_conductor_salir = new javax.swing.JButton();
        txt_informacion_conductor_usuario = new javax.swing.JTextField();
        txt_informacion_conductor_nombres = new javax.swing.JTextField();
        txt_informacion_conductor_cedula = new javax.swing.JTextField();
        txt_informacion_conductor_celular = new javax.swing.JTextField();
        txt_informacion_conductor_tipo_vehiculo = new javax.swing.JTextField();
        txt_informacion_conductor_matricula = new javax.swing.JTextField();
        txt_informacion_conductor_licencia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(43, 81, 132));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 118, 0));
        jLabel1.setText("Información del Conductor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Información del Vehículo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 170, 130));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombres y Apellidos:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cédula o Ruc:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Celular:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de Vehículo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Matrícula del Vehículo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo de Licencia:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 118, 0));
        jLabel11.setText("Valoración:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, 20));

        btn_informacion_conductor_calificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_informacion_conductor_calificar.setText("Calificar");
        jPanel1.add(btn_informacion_conductor_calificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        btn_informacion_conductor_salir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_informacion_conductor_salir.setText("Salir");
        jPanel1.add(btn_informacion_conductor_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, -1));
        jPanel1.add(txt_informacion_conductor_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 270, -1));
        jPanel1.add(txt_informacion_conductor_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 270, -1));
        jPanel1.add(txt_informacion_conductor_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 120, -1));
        jPanel1.add(txt_informacion_conductor_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 120, -1));
        jPanel1.add(txt_informacion_conductor_tipo_vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 270, -1));
        jPanel1.add(txt_informacion_conductor_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 270, -1));

        txt_informacion_conductor_licencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_informacion_conductor_licenciaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_informacion_conductor_licencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 270, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_informacion_conductor_licenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_informacion_conductor_licenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_informacion_conductor_licenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente_Informacion_Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente_Informacion_Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente_Informacion_Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente_Informacion_Conductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente_Informacion_Conductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_informacion_conductor_calificar;
    private javax.swing.JButton btn_informacion_conductor_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_informacion_conductor_cedula;
    private javax.swing.JTextField txt_informacion_conductor_celular;
    private javax.swing.JTextField txt_informacion_conductor_licencia;
    private javax.swing.JTextField txt_informacion_conductor_matricula;
    private javax.swing.JTextField txt_informacion_conductor_nombres;
    private javax.swing.JTextField txt_informacion_conductor_tipo_vehiculo;
    private javax.swing.JTextField txt_informacion_conductor_usuario;
    // End of variables declaration//GEN-END:variables
}
