package views;

import controlador.Inicio_SesionControlador;
import modelo.*;

public class Iniciar_Sesion extends javax.swing.JFrame {
    RegistroCliente cliente = new RegistroCliente();
    Registro_ClienteDao cliente_dao = new Registro_ClienteDao();
    RegistroSocio socio = new RegistroSocio();
    Registro_SocioDao socio_dao = new Registro_SocioDao();


    /**
     * Creates new form Inicar_Sesion
     */
    public Iniciar_Sesion() {
        initComponents();
        setSize(649, 510);//Para que se queden las medidas que le dimos
        setResizable(false);//Para que el usuario no pueda modificar el tamaño.
        setTitle("Iniciar Sesión");//Para colocar un titulo a la ventana
        setLocationRelativeTo(null);//Impide mover la ventana
         this.repaint();
         
         //Controlador del inicio de sesion
         Inicio_SesionControlador usuario_sesion = new Inicio_SesionControlador(cliente, cliente_dao, socio, socio_dao, this);
         
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_sesion_cancelar = new javax.swing.JButton();
        btn_sesion_aceptar = new javax.swing.JButton();
        txt_sesion_usuario = new javax.swing.JTextField();
        txt_sesion_contrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(649, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Iniciar Sesión");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Usuario:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/User_icon.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 160, 120));

        btn_sesion_cancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_sesion_cancelar.setText("Cancelar");
        btn_sesion_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sesion_cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sesion_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, -1, -1));

        btn_sesion_aceptar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_sesion_aceptar.setText("Aceptar");
        btn_sesion_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sesion_aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sesion_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        txt_sesion_usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_sesion_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sesion_usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txt_sesion_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 180, -1));

        txt_sesion_contrasenia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_sesion_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sesion_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sesion_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sesion_usuarioActionPerformed

    private void btn_sesion_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sesion_cancelarActionPerformed
Login_view login = new Login_view();
login.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btn_sesion_cancelarActionPerformed

    private void btn_sesion_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sesion_aceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sesion_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciar_Sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_sesion_aceptar;
    public javax.swing.JButton btn_sesion_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField txt_sesion_contrasenia;
    public javax.swing.JTextField txt_sesion_usuario;
    // End of variables declaration//GEN-END:variables
}
