
package views;

import controlador.Registro_ClienteControlador;
import modelo.RegistroCliente;
import modelo.Registro_ClienteDao;


public class Registro_Cliente extends javax.swing.JFrame {
    RegistroCliente Cliente = new RegistroCliente();
    Registro_ClienteDao clienteDao = new Registro_ClienteDao();
    

    /**
     * Creates new form Registro_Cliente
     */
    public Registro_Cliente() {
        initComponents();
        setSize(649, 510);//Para que se queden las medidas que le dimos
        setResizable(false);//Para que el usuario no pueda modificar el tamaño.
        setTitle("Registro - Cliente");//Para colocar un titulo a la ventana
        setLocationRelativeTo(null);//Impide mover la ventana
        this.repaint();
        
        //Controlador del registro de cliente
        Registro_ClienteControlador cliente_cuenta = new Registro_ClienteControlador(Cliente, clienteDao, this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_registro_cliente_registrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_registro_cliente_nombres = new javax.swing.JTextField();
        txt_registro_cliente_cedula = new javax.swing.JTextField();
        txt_registro_cliente_celular = new javax.swing.JTextField();
        txt_registro_cliente_email = new javax.swing.JTextField();
        txt_registro_cliente_usuario = new javax.swing.JTextField();
        txt_registro_cliente_contraseña = new javax.swing.JTextField();
        txt_registro_cliente_confirmar_contraseña = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_registro_cliente_provincia = new javax.swing.JTextField();
        jL_cliente_rol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(649, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre y Apellido:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cédula:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Celular:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Provincia:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo Electrónico:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre de Usuario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirmar Contraseña:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        btn_registro_cliente_registrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_registro_cliente_registrar.setText("Registrarse");
        jPanel1.add(btn_registro_cliente_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("UBER - CLIENTE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));
        jPanel1.add(txt_registro_cliente_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 170, -1));
        jPanel1.add(txt_registro_cliente_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 110, -1));
        jPanel1.add(txt_registro_cliente_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 110, -1));
        jPanel1.add(txt_registro_cliente_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 240, -1));
        jPanel1.add(txt_registro_cliente_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 210, -1));
        jPanel1.add(txt_registro_cliente_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 210, -1));
        jPanel1.add(txt_registro_cliente_confirmar_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 210, -1));

        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 120, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 130, 100));
        jPanel1.add(txt_registro_cliente_provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 240, -1));

        jL_cliente_rol.setForeground(new java.awt.Color(0, 0, 51));
        jL_cliente_rol.setText("CLIENTE");
        jPanel1.add(jL_cliente_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_registro_cliente_registrar;
    public javax.swing.JLabel jL_cliente_rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_registro_cliente_cedula;
    public javax.swing.JTextField txt_registro_cliente_celular;
    public javax.swing.JTextField txt_registro_cliente_confirmar_contraseña;
    public javax.swing.JTextField txt_registro_cliente_contraseña;
    public javax.swing.JTextField txt_registro_cliente_email;
    public javax.swing.JTextField txt_registro_cliente_nombres;
    public javax.swing.JTextField txt_registro_cliente_provincia;
    public javax.swing.JTextField txt_registro_cliente_usuario;
    // End of variables declaration//GEN-END:variables
}
