package views;

public class Socio extends javax.swing.JFrame {

    /**
     * Interfaz de socio 
     */
    public Socio() {
        initComponents();
        setSize(1000, 560);//Para que se queden las medidas que le dimos
        setResizable(false);//Para que el usuario no pueda modificar el tamaño.
        setTitle("SOCIO");//Para colocar un titulo a la ventana
        setLocationRelativeTo(null);//Impide mover la ventana
         this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        txt_ofrecer_servicio1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_detalles_servicio1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        txt_ofrecer_servicio2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btn_detalles_servicio2 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        txt_ofrecer_servicio3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btn_detalles_servicio3 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        txt_destino_direccion1 = new javax.swing.JTextField();
        txt_destino_fecha1 = new javax.swing.JTextField();
        btn_destino_detalle1 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        btn_destino_detalle2 = new javax.swing.JButton();
        txt_destino_direccion2 = new javax.swing.JTextField();
        txt_destino_fecha2 = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        txt_destino_direccion3 = new javax.swing.JTextField();
        txt_destino_fecha3 = new javax.swing.JTextField();
        btn_destino_detalle3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        btn_configuracion_socio_editar_foto = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_configuracion_socio_usuario = new javax.swing.JTextField();
        txt_configuracion_socio_nombres = new javax.swing.JTextField();
        txt_configuracion_socio_cedula = new javax.swing.JTextField();
        txt_configuracion_socio_celular = new javax.swing.JTextField();
        txt_configuracion_socio_provincia = new javax.swing.JTextField();
        txt_configuracion_socio_email = new javax.swing.JTextField();
        txt_configuracion_socio_vehiculo = new javax.swing.JTextField();
        txt_configuracion_socio_matricula = new javax.swing.JTextField();
        btn_configuracion_socio_cancelar = new javax.swing.JButton();
        btn_configuracion_socio_guardar = new javax.swing.JButton();
        btn_configuracion_socio_contrasenia = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(242, 120, 29));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(242, 120, 29));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 110));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("Bienvenido al Sistema Uber");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("\"Socio\"");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Cerrar Sesión");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 110));

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("  Elija una opción a realizar");
        jLabel4.setAutoscrolls(true);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 40));

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        jLabel2.setBackground(new java.awt.Color(255, 255, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Ofrecer Servicio      ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));

        jLabel3.setBackground(new java.awt.Color(255, 255, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Agenda de Viajes      ");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 102));

        jLabel5.setBackground(new java.awt.Color(255, 255, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Actividad      ");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 102));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Configuración      ");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 190, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 190, 430));

        jPanel16.setBackground(new java.awt.Color(74, 101, 191));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_ofrecer_servicio1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel17.add(txt_ofrecer_servicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 172, 25));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText(" - ¡Está solicitando un viaje!");
        jPanel17.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 24, 228, -1));

        btn_detalles_servicio1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_detalles_servicio1.setText("Detalles");
        jPanel17.add(btn_detalles_servicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 21, 91, -1));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 660, 70));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 118, 0));
        jLabel14.setText("Servicio");
        jPanel16.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_ofrecer_servicio2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel18.add(txt_ofrecer_servicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 23, 172, 25));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText(" - ¡Está solicitando un viaje!");
        jPanel18.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 27, 228, -1));

        btn_detalles_servicio2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_detalles_servicio2.setText("Detalles");
        jPanel18.add(btn_detalles_servicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 24, 91, -1));

        jPanel16.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 660, 70));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_ofrecer_servicio3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel19.add(txt_ofrecer_servicio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 24, 172, 25));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText(" - ¡Está solicitando un viaje!");
        jPanel19.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 28, 228, -1));

        btn_detalles_servicio3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_detalles_servicio3.setText("Detalles");
        jPanel19.add(btn_detalles_servicio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 25, 91, -1));

        jPanel16.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 660, 70));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel8);

        jPanel12.setBackground(new java.awt.Color(74, 101, 191));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 118, 0));
        jLabel7.setText("Agenda de Viajes");
        jPanel12.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setForeground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(txt_destino_direccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 25));
        jPanel15.add(txt_destino_fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 150, 25));

        btn_destino_detalle1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_destino_detalle1.setText("Detalles");
        jPanel15.add(btn_destino_detalle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 21, -1, -1));

        jPanel12.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 660, 70));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setForeground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_destino_detalle2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_destino_detalle2.setText("Detalles");
        jPanel20.add(btn_destino_detalle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 21, 91, -1));
        jPanel20.add(txt_destino_direccion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 25));
        jPanel20.add(txt_destino_fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 150, 25));

        jPanel12.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 660, 70));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setForeground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(txt_destino_direccion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 25));
        jPanel21.add(txt_destino_fecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 150, 25));

        btn_destino_detalle3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_destino_detalle3.setText("Detalles");
        jPanel21.add(btn_destino_detalle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 21, -1, -1));

        jPanel12.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 660, 70));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel9);

        jPanel13.setBackground(new java.awt.Color(74, 101, 191));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 120, 29));
        jLabel8.setText("Historial de Viajes");
        jPanel13.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 340, 80));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Elija una opción a revisar");
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("jLabel12");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 204));
        jLabel17.setText("Viaje en Curso");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 200, 190));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("jLabel18");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 204));
        jLabel19.setText("Viajes Realizados");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(15, 15, 15))
        );

        jPanel13.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 200, 190));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel10);

        jPanel11.setBackground(new java.awt.Color(74, 101, 191));

        jPanel14.setBackground(new java.awt.Color(74, 101, 191));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("jLabel20");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 100));

        btn_configuracion_socio_editar_foto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_configuracion_socio_editar_foto.setText("Editar Foto");
        jPanel14.add(btn_configuracion_socio_editar_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Usuario:");
        jPanel14.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Nombres y Apellidos");
        jPanel14.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Cedula o Ruc:");
        jPanel14.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Provincia:");
        jPanel14.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Celular:");
        jPanel14.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Correo Electrónico:");
        jPanel14.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Tipo de Vehiculo:");
        jPanel14.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Matricula:");
        jPanel14.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));
        jPanel14.add(txt_configuracion_socio_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 290, -1));
        jPanel14.add(txt_configuracion_socio_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 290, -1));
        jPanel14.add(txt_configuracion_socio_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 130, -1));
        jPanel14.add(txt_configuracion_socio_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 130, -1));
        jPanel14.add(txt_configuracion_socio_provincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 290, -1));
        jPanel14.add(txt_configuracion_socio_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 290, -1));
        jPanel14.add(txt_configuracion_socio_vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 200, -1));
        jPanel14.add(txt_configuracion_socio_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 200, -1));

        btn_configuracion_socio_cancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_configuracion_socio_cancelar.setText("Cancelar");
        jPanel14.add(btn_configuracion_socio_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        btn_configuracion_socio_guardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_configuracion_socio_guardar.setText("Guardar");
        jPanel14.add(btn_configuracion_socio_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

        btn_configuracion_socio_contrasenia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_configuracion_socio_contrasenia.setText("Cambiar Contraseña");
        jPanel14.add(btn_configuracion_socio_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        jLabel29.setText("jLabel29");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 100, 80));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel11);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 810, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Socio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_configuracion_socio_cancelar;
    private javax.swing.JButton btn_configuracion_socio_contrasenia;
    private javax.swing.JButton btn_configuracion_socio_editar_foto;
    private javax.swing.JButton btn_configuracion_socio_guardar;
    private javax.swing.JButton btn_destino_detalle1;
    private javax.swing.JButton btn_destino_detalle2;
    private javax.swing.JButton btn_destino_detalle3;
    private javax.swing.JButton btn_detalles_servicio1;
    private javax.swing.JButton btn_detalles_servicio2;
    private javax.swing.JButton btn_detalles_servicio3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_configuracion_socio_cedula;
    private javax.swing.JTextField txt_configuracion_socio_celular;
    private javax.swing.JTextField txt_configuracion_socio_email;
    private javax.swing.JTextField txt_configuracion_socio_matricula;
    private javax.swing.JTextField txt_configuracion_socio_nombres;
    private javax.swing.JTextField txt_configuracion_socio_provincia;
    private javax.swing.JTextField txt_configuracion_socio_usuario;
    private javax.swing.JTextField txt_configuracion_socio_vehiculo;
    private javax.swing.JTextField txt_destino_direccion1;
    private javax.swing.JTextField txt_destino_direccion2;
    private javax.swing.JTextField txt_destino_direccion3;
    private javax.swing.JTextField txt_destino_fecha1;
    private javax.swing.JTextField txt_destino_fecha2;
    private javax.swing.JTextField txt_destino_fecha3;
    private javax.swing.JTextField txt_ofrecer_servicio1;
    private javax.swing.JTextField txt_ofrecer_servicio2;
    private javax.swing.JTextField txt_ofrecer_servicio3;
    // End of variables declaration//GEN-END:variables
}
