package views;

public class Socio_Viajes_Completos extends javax.swing.JFrame {

    /**
     * Creates new form Socio_Viajes_Completos
     */
    public Socio_Viajes_Completos() {
        initComponents();
        setSize(720, 520);//Para que se queden las medidas que le dimos
        setResizable(false);//Para que el usuario no pueda modificar el tamaño.
        setTitle("Viajes Completados");//Para colocar un titulo a la ventana
        setLocationRelativeTo(null);//Centra la pantalla
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_completado_atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viajes_completados_table = new javax.swing.JTable();
        txt_completado_id = new javax.swing.JTextField();
        txt_completado_fecha_viaje = new javax.swing.JTextField();
        txt_completado_destino = new javax.swing.JTextField();
        txt_completado_precio = new javax.swing.JTextField();
        txt_completado_nombre = new javax.swing.JTextField();
        txt_completado_buscar = new javax.swing.JTextField();
        btn_completado_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 81, 132));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_completado_atras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_completado_atras.setText("Atrás");
        jPanel1.add(btn_completado_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 118, 0));
        jLabel1.setText("Viajes Completados");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de Viaje:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destino:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre del Cliente:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Buscar:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 20));

        viajes_completados_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Destino", "Precio", "Nombre del Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        viajes_completados_table.setMinimumSize(new java.awt.Dimension(105, 0));
        viajes_completados_table.setPreferredSize(new java.awt.Dimension(410, 0));
        jScrollPane1.setViewportView(viajes_completados_table);
        if (viajes_completados_table.getColumnModel().getColumnCount() > 0) {
            viajes_completados_table.getColumnModel().getColumn(0).setResizable(false);
            viajes_completados_table.getColumnModel().getColumn(0).setPreferredWidth(10);
            viajes_completados_table.getColumnModel().getColumn(1).setResizable(false);
            viajes_completados_table.getColumnModel().getColumn(2).setResizable(false);
            viajes_completados_table.getColumnModel().getColumn(3).setResizable(false);
            viajes_completados_table.getColumnModel().getColumn(3).setPreferredWidth(20);
            viajes_completados_table.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 660, 150));
        jPanel1.add(txt_completado_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, -1));
        jPanel1.add(txt_completado_fecha_viaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 170, -1));
        jPanel1.add(txt_completado_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 220, -1));
        jPanel1.add(txt_completado_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 60, -1));
        jPanel1.add(txt_completado_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 165, -1));
        jPanel1.add(txt_completado_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 230, -1));

        btn_completado_buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_completado_buscar.setText("Buscar Viaje");
        jPanel1.add(btn_completado_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Socio_Viajes_Completos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Socio_Viajes_Completos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Socio_Viajes_Completos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Socio_Viajes_Completos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Socio_Viajes_Completos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_completado_atras;
    private javax.swing.JButton btn_completado_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_completado_buscar;
    private javax.swing.JTextField txt_completado_destino;
    private javax.swing.JTextField txt_completado_fecha_viaje;
    private javax.swing.JTextField txt_completado_id;
    private javax.swing.JTextField txt_completado_nombre;
    private javax.swing.JTextField txt_completado_precio;
    private javax.swing.JTable viajes_completados_table;
    // End of variables declaration//GEN-END:variables
}
